Python 2.7:
  script:
  - py_version=2.7
  - EXTRA_INSTALL=numpy
  - echo "BOOST_BINDINGS_INC_DIR = ['boost-numeric-bindings']" > siteconf.py
  - if ! test -d boost-numeric-bindings; then git clone http://git.tiker.net/trees/boost-numeric-bindings.git; fi
  - if ! test -d ./test/boost-numeric-bindings; then (cd test; ln -s ../boost-numeric-bindings); fi
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python2.7
  except:
  - tags
